### ISSUE TITLE
UI is too low-contrast

### ISSUE THREAD

**Issue by bryankaplan** [samuelclay/NewsBlur#1684]
In dark mode, the greys are way too light, making much of the text illegible to my eyes. The background could be a pure black, or close to it.

**Comment by samuelclay** [comment]
Got a screenshot you can annotate?

**Comment by bryankaplan** [comment]
Thank you for your patience. Here are two screenshots.
* Screenshot A depicts the current UI in dark mode, marked up to indicate four regions (described below).
* Screenshot B depicts the UI with improved contrast. This is NewsBlur as I personally use it, given my userContent.css (included below).

### Screenshot A
![Image](https://github.com/user-attachments/assets/b2afab80-b746-441a-91af-8daec11800b1)

### Region Descriptions

1. Region A: Extreme low-contrast, nearly impossible to read.
2. Region B: Slightly better than A, but still low-contrast. These are feed names, redacted for my privacy.
3. Region C: Same as A.
4. Region D: These article titles are the best of the four sections, yet they're still low-contrast.

### Screenshot B
![Image](https://github.com/user-attachments/assets/ce7b6515-f880-4593-956b-c9f0649c15a6)

### userContent.css snippet

```css
@-moz-document domain(newsblur.com) {
    .NB-dark .NB-feeds-header {
        background-color: #222 !important;
    }
    .NB-dark .NB-feeds-header.NB-selected {
        background-color: #334 !important;
    }
    .NB-dark .NB-feeds-header-user,
    .ui-layout-pane.ui-layout-pane-north,
    .NB-dark .left-pane, .NB-dark .NB-feedlist,
    .NB-dark .NB-feedlist .feed,
    .NB-dark .NB-story-title {
        background-color: #000 !important;
    }
    .NB-dark #story_titles .NB-story-title.NB-selected.read a.story_title
            .NB-storytitles-title {
        color: #DDB !important;
    }
    .feed_favicon {
        background-color: #FFF !important;
        opacity: 0.85 !important;
    }
}
```
