### ISSUE TITLE
RAM usage

### ISSUE THREAD

**Issue by VlaK0r** [samuelclay/NewsBlur#1848]
Hello!
Thank you for your hard work.

The instance is installed on raspberrypi (Debian GNU/Linux 12 64bit / Linux 6.1.0-rpi8-rpi-v8)

![image](https://github.com/samuelclay/NewsBlur/assets/77666575/36d22c99-765e-4dde-aed0-38be91b792aa)
![image](https://github.com/samuelclay/NewsBlur/assets/77666575/cff08a52-3e22-4922-95fd-f3e15dbb488c)
![image](https://github.com/samuelclay/NewsBlur/assets/77666575/3afeca6a-c640-44d6-a868-b60c9b8cbdba)

The installation uses a large amount of RAM.
But after the installation is finished, the RAM remains occupied, plus it starts to fill up SWAP.
If you stop the db_elasticsearch container, then the consumption of RAM drops significantly.

Please tell me, is this the normal state of a working NewsBlur? Or is something not working correctly?

**Comment by VlaK0r** [comment]
```
  db_elasticsearch:
    container_name: db_elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    mem_limit: 512mb
```
I found this line in the file `docker-compose.yml`
But it turns out that this restriction does not work.
